name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: 'true'

  build:
    runs-on: windows-latest

    steps:
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          gradlew nativeCompile
          mv app/build/native/nativeCompile/app.exe PCBooster.exe

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/native/nativeCompile/PCBooster.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
