name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          ./gradlew nativeCompile
          mv app/build/native/nativeCompile/app.exe PCBooster.exe

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: PCBooster.exe
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release artifacts for ${{ github.ref }}
            - Executable: ${{ steps.upload_artifact.outputs.artifact_url }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PCBooster.exe
          asset_name: PCBooster.exe
          asset_content_type: application/octet-stream
