name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-Release
          path: windows-release

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-Release
          path: macos-release

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-Release
          path: ubuntu-release

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "This release contains the following packages:\n- Windows: windows-release\n- macOS: macos-release\n- Ubuntu: ubuntu-release"

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows-release
          asset_name: PCBooster-windows.exe
          asset_content_type: application/x-msdownload

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: macos-release
          asset_name: PCBooster-macos
          asset_content_type: application/x-zip-compressed

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ubuntu-release
          asset_name: PCBooster-ubuntu
          asset_content_type: application/x-zip-compressed
