name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for this release'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-Release
          path: ubuntu-Release

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-Release
          path: macos-Release

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-Release
          path: windows-Release

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'ubuntu-Release/PCBooster,macos-Release/PCBooster,windows-Release/PCBooster.exe'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          allowUpdates: true
          replacesArtifacts: true
