name: Perform release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  perform-release-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew nativeCompile

      - name: Create Release Directory
        run: |
          mkdir -p release/linux
          cp app/build/native/nativeCompile/PCBooster release/linux/PCBooster

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/linux/PCBooster
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  perform-release-macos:
    runs-on: macos-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew nativeCompile

      - name: Create Release Directory
        run: |
          mkdir -p release/macos
          cp app/build/native/nativeCompile/PCBooster release/macos/PCBooster

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/macos/PCBooster
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  perform-release-windows:
    runs-on: windows-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew nativeCompile

      - name: Create Release Directory
        run: |
          mkdir -p release/windows
          cp app/build/native/nativeCompile/PCBooster.exe release/windows/PCBooster.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/windows/PCBooster.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
