name: Build Ubuntu Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build-ubuntu:
    permissions:
      contents: write
    name: PCBooster on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew nativeCompile

      - name: Create Release Directory
        run: mkdir release

      - name: Move Artifact to Release Directory
        run: mv app/build/native/nativeCompile/PCBooster release/linux/

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-Release
          path: release/linux/PCBooster
          if-no-files-found: error
      - name: Set build completion output
        run: echo "build_completed=true" >> $GITHUB_OUTPUT
