name: Build Ubuntu Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build-ubuntu:
    permissions:
      contents: write
    name: PCBooster on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew nativeCompile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-Release
          path: app/build/native/nativeCompile/PCBooster

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'app/build/native/nativeCompile/PCBooster'
          token: ${{ secrets.GITHUB_TOKEN }}
